version: '3.3'

services:
  storesmanagementdb:
    container_name: storesmanagementdb
    image: mysql:5.7.8
    environment:
      MYSQL_DATABASE: storesmanagementdb
      MYSQL_USER: webuser
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - default
    volumes:
      - storesmanagementdbvolume:/var/lib/mysql
    expose:
      - 3306

  stores_management-web:
    restart: always
    build: .
    container_name: stores_management-web
    entrypoint: /stores-management/bin/run_stores_management_web.sh
    ports:
      - "8081:8081"
    volumes:
      - .:/stores-management
    networks:
      - default

volumes:
  storesmanagementdbvolume:
